---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: heading
  label: Content
- type: directory
  path: docs
  label: Docs
  create: all
  match: "**/*"
  templates:
  - documentation-page
- type: heading
  label: Settings
- type: document
  path: data/settings.json
  label: Menu
upload_dir: static
public_path: ''
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - GRAPHQL_ENDPOINT=/___graphql
  preview_output_directory: public
  install_dependencies_command: npm install --save @gridsome/cli
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run forestry-preview
